#!/bin/python3
import json
import shodan
import sys

#IPAddr = input("Please Enter IP to Lookup: ")
SHODAN_API_KEY = "YOUR API KEY HERE"

api = shodan.Shodan(SHODAN_API_KEY)

#Takes a text file named ipaddr.txt with a single IP address on each line
txt_file = open("ipaddr.txt","r")
for IPAddr in txt_file.read().splitlines():

        try:
                # Lookup the host
                host = api.host(IPAddr)

                output = " Results for " + IPAddr + ":\n Ports Found: : " + str(host.get('ports','n/a')) +  "\n Vulnerablities Found: " + str(host.get('vulns','n/a'))

                for item in host['data']:
                        if item.get('vulns'):
                                output += '{}'.format(json.dumps(item.get('vulns'),indent=3),'') + "\n\n"

                with open('output.txt','a') as f:
                        f.write(output)

        except Exception as e:
                output = "Results for " + IPAddr + ": " + 'Error {}'.format(e) + "\n"

                with open('output.txt','a') as f:
                        f.write(output)
