#!/bin/python3
import json
import shodan
import sys
import time
import itertools
import threading

start_time = time.time()
done = False
def animate():
    for c in itertools.cycle(['|', '/', '-', '\\']):
        if done:
            break
        sys.stdout.write('\rLoading ' + c)
        sys.stdout.flush()
        time.sleep(0.1)
    sys.stdout.write('\rDone!     ')
t = threading.Thread(target=animate)
t.daemon = True
t.start()

SHODAN_API_KEY = "YOUR API KEY HERE"

api = shodan.Shodan(SHODAN_API_KEY)

with open('output.json','w') as f:
        f.write("")
        f.close()

txt_file = open("ipaddr.txt","r")
for IPAddr in txt_file.read().splitlines():

        try:
                # Lookup the host
                host = api.host(IPAddr)

                output = " \"Results for " + row['ip'] + " " + row['name'] + "\":\n \"Last Updated\": \"" + str(host['last_update']) + "\"\n \"Ports Found\": " + str(host.get('ports','\"n/a\"\n')) +  "\n \"Vulnerablities Found\": \"" + str(host.get('vulns','n/a')) + "\"\n\n"

                for item in host['data']:
                        if item.get('vulns'):
                                output += '{}'.format(json.dumps(item.get('vulns'),indent=3),'') + "\n\n"

                with open('output.json','a') as f:
                        f.write(output)

        except Exception as e:
                output = " Results for " + IPAddr + ": " + 'Error {}'.format(e) + "\n\n"

                with open('output.json','a') as f:
                        f.write(output)
done = True
print("--- %s seconds ---" % (time.time() - start_time))
