#!/bin/python3
import json
import shodan
import sys

IPAddr = input("Please Enter IP to Lookup: ")
SHODAN_API_KEY = "YOUR API KEY HERE"

api = shodan.Shodan(SHODAN_API_KEY)

try:
        # Lookup the host
        host = api.host(IPAddr)

        output = " \"Results for " + row['ip'] + " " + row['name'] + "\":\n \"Last Updated\": \"" + str(host['last_update']) + "\"\n \"Ports Found\": " + str(host.get('ports','\"n/a\"\n')) +  "\n \"Vulnerablities Found\": \"" + str(host.get('vulns','n/a')) + "\"\n\n"

        for item in host['data']:
                if item.get('vulns'):
                        output += '{}'.format(json.dumps(item.get('vulns'),indent=3),'')

        with open('output.json','w') as f:
                f.write(output)

except Exception as e:
        output = "Results for " + IPAddr + ": " + 'Error {}'.format(e) + "\n"

        with open('output.json','w') as f:
                f.write(output)
